server:
  port: 8081

spring:
  application:
    name: Service-2

eureka:
  instance:
    host: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost2:8762/eureka/